dbt_code:
  outputs:
    dev:
      account: YOUR ACCOUNT IDENTIFIER
      database: YOUR DATABASE
      password: YOUR PASSWORD
      role: YOUR ROLE
      schema: YOUR SCHEMA
      threads: 1
      type: snowflake
      user: USER NAME
      warehouse: WAREHOUSE NAME
  target: dev

