[project]
name = "hospitality-analytics-pipeline-using-snowflake-and-dbt-medallion-architecture"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.11.7",
    "dbt-snowflake>=1.11.3",
]

[dependency-groups]
dev = [
    "pytest>=8.0.0",
    "pytest-bdd>=8.0.0",
    "sqlparse>=0.5.0",
]
